/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { Button } from "@/components/ui/button";
import { useProfile } from "@/src/context/ProfileContext";
import { motion } from "motion/react";
import { CheckCircle2, ShieldCheck, Zap, BarChart3, Clock, Users, ArrowRight, GraduationCap, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function LandingPage() {
  const { profile } = useProfile();
  const navigate = useNavigate();

  return (
    <div className="flex flex-col min-h-screen bg-slate-50">
      {/* Hero Section */}
      <section className="relative pt-24 pb-40 overflow-hidden bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 text-blue-600 font-black text-[10px] uppercase tracking-widest mb-8 border border-blue-100 shadow-sm">
                <Sparkles className="w-3 h-3" />
                Next-Gen Computer Based Testing
              </div>
              <h1 className="text-6xl sm:text-8xl font-black tracking-tight text-slate-900 mb-8 font-sans leading-[0.9]">
                Master Your Exams <br />
                <span className="text-blue-600">With Confidence</span>
              </h1>
              <p className="text-xl text-slate-500 mb-12 max-w-2xl mx-auto font-medium leading-relaxed">
                Ark Academy CBT is a local-first platform designed to help Primary 3, JSS 3, SS 1, and JSSCE (WAEC) students excel through personalized testing.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                {profile ? (
                  <Button size="lg" className="text-xl px-10 h-16 font-black rounded-2xl shadow-2xl shadow-blue-600/30 bg-blue-600 hover:bg-blue-700 transition-all hover:scale-105 group" onClick={() => navigate("/dashboard")}>
                    {profile.isAdmin ? "Admin Dashboard" : "Go to My Dashboard"}
                    <ArrowRight className="ml-2 group-hover:translate-x-1 transition-transform" />
                  </Button>
                ) : (
                  <>
                    <Button size="lg" className="text-xl px-10 h-16 font-black rounded-2xl shadow-2xl shadow-blue-600/30 bg-blue-600 hover:bg-blue-700 transition-all hover:scale-105 group" onClick={() => navigate("/onboarding")}>
                      Student Access
                      <GraduationCap className="ml-2 w-6 h-6" />
                    </Button>
                    <Button variant="outline" size="lg" className="text-xl px-8 h-16 font-bold border-2 border-slate-200 rounded-2xl hover:bg-slate-50 text-slate-700" onClick={() => navigate("/onboarding?tab=admin")}>
                      Admin Access
                      <ShieldCheck className="ml-2 w-6 h-6" />
                    </Button>
                  </>
                )}
              </div>
            </motion.div>
          </div>
        </div>

        {/* Decorative Background Elements */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full pointer-events-none overflow-hidden -z-10">
          <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-blue-50 rounded-full blur-[120px] opacity-60 animate-pulse" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-indigo-50 rounded-full blur-[120px] opacity-60" />
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-slate-900 mb-6 tracking-tight">Everything You Need To Excel</h2>
            <p className="text-slate-500 text-lg font-medium max-w-xl mx-auto leading-relaxed">Local-first for speed, cloud-ready for peace of mind. Your progress is always safe.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
            <FeatureCard
              icon={<Zap className="w-8 h-8 text-blue-600" />}
              title="AI-Powered Quizzes"
              description="Dynamic quizzes generated by Gemini AI tailored to your specific class and syllabus topics."
            />
            <FeatureCard
              icon={<BarChart3 className="w-8 h-8 text-blue-600" />}
              title="Live Analytics"
              description="Track your mastery over time with visual insights into your strongest and weakest academic areas."
            />
            <FeatureCard
              icon={<Clock className="w-8 h-8 text-blue-600" />}
              title="Instant Feedback"
              description="Receive 1-on-1 AI-teacher feedback after every session to help you understand your mistakes."
            />
          </div>
        </div>
      </section>

      {/* Preview Section */}
      <section className="py-32 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row items-center gap-20">
            <div className="lg:w-1/2">
              <h2 className="text-5xl font-black text-slate-900 mb-8 leading-[1.1] tracking-tight">A Modern Interface <br /> Built for Focus</h2>
              <p className="text-xl text-slate-500 mb-10 font-medium leading-relaxed">
                We've eliminated distractions to create a clean, purposeful testing environment that helps students concentrate on what matters: their learning.
              </p>
              <ul className="space-y-6 mb-12">
                <LevelItem title="Primary 3: Fundamentals" description="Engaging visuals and clear instruction for young learners." />
                <LevelItem title="JSS 3: Transition" description="Comprehensive preparation for secondary school transitions." />
                <LevelItem title="SS 1: Specialization" description="Targeted paths for Science, Arts, and Commercial departments." />
              </ul>
              <Button size="lg" variant="outline" className="h-14 px-8 border-slate-200 rounded-2xl font-bold font-sans text-slate-900" onClick={() => navigate("/onboarding")}>
                 Get Started for Free
              </Button>
            </div>
            <div className="lg:w-1/2 relative">
               <div className="bg-slate-900 rounded-[2.5rem] p-1 shadow-2xl transform rotate-3 hover:rotate-0 transition-transform duration-700">
                  <div className="bg-white rounded-[2rem] overflow-hidden border border-slate-800">
                     <div className="bg-slate-50 border-b border-slate-100 p-4 flex items-center justify-between">
                        <div className="flex gap-2">
                           <div className="w-3 h-3 rounded-full bg-red-400" />
                           <div className="w-3 h-3 rounded-full bg-yellow-400" />
                           <div className="w-3 h-3 rounded-full bg-green-400" />
                        </div>
                        <div className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Ark Academy Simulator</div>
                     </div>
                     <div className="p-8 space-y-8">
                        <div className="space-y-2">
                           <div className="flex justify-between text-xs font-bold text-slate-400">
                              <span>Question 7 of 20</span>
                              <span className="text-blue-600">65% Progress</span>
                           </div>
                           <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                              <div className="h-full bg-blue-600 w-2/3" />
                           </div>
                        </div>
                        <div className="space-y-6">
                           <h4 className="text-xl font-bold text-slate-900">What is the primary function of the root in a flowering plant?</h4>
                           <div className="space-y-3">
                              <div className="p-4 border-2 border-slate-100 rounded-xl text-sm font-bold text-slate-600 hover:bg-slate-50 cursor-pointer">A) Carry out photosynthesis</div>
                              <div className="p-4 border-2 border-blue-600 bg-blue-50 rounded-xl text-sm font-black text-blue-900 shadow-lg shadow-blue-500/10">B) Absorbs water and minerals</div>
                              <div className="p-4 border-2 border-slate-100 rounded-xl text-sm font-bold text-slate-600 hover:bg-slate-50 cursor-pointer">C) Produce seeds for reproduction</div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div className="absolute -bottom-10 -left-10 bg-white p-6 rounded-3xl shadow-xl border border-slate-100 max-w-[200px] animate-bounce">
                  <div className="flex items-center gap-3 mb-2">
                    <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center text-green-600">
                      <Zap className="w-4 h-4" />
                    </div>
                    <span className="font-black text-xs">AI Teacher</span>
                  </div>
                  <p className="text-[10px] text-slate-400 leading-relaxed font-bold italic">"Excellent! You've correctly identified the root's absorption function."</p>
               </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-50 border-t border-slate-100 py-20 px-4">
         <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-10">
            <div className="flex items-center gap-3">
               <div className="w-10 h-10 bg-blue-600 rounded-xl flex items-center justify-center text-white font-black">AA</div>
               <span className="font-black text-lg tracking-tighter">Ark Academy</span>
            </div>
            <p className="text-slate-400 text-sm font-bold">© 2024 Ark Academy CBT. Built for the future of learning.</p>
         </div>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <motion.div
      whileHover={{ y: -8, scale: 1.02 }}
      className="p-10 bg-white rounded-[2.5rem] border border-slate-50 shadow-xl shadow-slate-200/40 hover:shadow-blue-600/10 transition-all group"
    >
      <div className="w-16 h-16 bg-slate-50 rounded-2xl flex items-center justify-center mb-8 group-hover:bg-blue-600 group-hover:text-white transition-colors duration-500">
        {icon}
      </div>
      <h3 className="text-2xl font-black text-slate-900 mb-4 tracking-tight leading-none">{title}</h3>
      <p className="text-slate-500 leading-relaxed font-medium">{description}</p>
    </motion.div>
  );
}

function LevelItem({ title, description }: { title: string; description: string }) {
  return (
    <li className="flex gap-4 items-start">
      <div className="mt-1 flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center shadow-lg shadow-blue-600/30">
        <CheckCircle2 className="w-4 h-4" />
      </div>
      <div>
        <h4 className="font-black text-slate-900 text-lg leading-tight mb-1">{title}</h4>
        <p className="text-sm text-slate-500 font-medium">{description}</p>
      </div>
    </li>
  );
}
